[package]
name = "args-parser"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Bruno Flavio Ferreira"]
description = "A CLI arguments parser library"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
